"""Auto migration

Revision ID: c688664d1279
Revises: f599860d4d73
Create Date: 2025-07-05 12:00:16.243419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c688664d1279'
down_revision = 'f599860d4d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###