"""Auto migration

Revision ID: db3a0672d229
Revises: c688664d1279
Create Date: 2025-07-05 12:20:16.803301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3a0672d229'
down_revision = 'c688664d1279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###