"""Auto migration

Revision ID: e85e96f18e1a
Revises: c5e8cc359327
Create Date: 2025-07-05 09:11:21.945544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85e96f18e1a'
down_revision = 'c5e8cc359327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###